version: 2.1

orbs:
  android: circleci/android@0.2.1

jobs:
  build:
    working_directory: ~/audiolearning
    executor: android/android
        
    steps:
      - checkout
      - run:
          command: chmod +x ./gradlew
      - run:
          command: ./gradlew build
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
